# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.create(email: "user@wepov.com", password: "12341234", password_confirmation: "12341234")
Debate.create(user_id: 1, title: "2015 한국사 교과서 국정화 논쟁", content: "검정 국사 교과서 중 보수적인 논조였던 교학사의 고등학교 역사교과서가 부실 논란 후 검정 취소되었다. 이후, 검정교과서의 대다수가 '국사를 부정적으로 서술'하며, '좌편향'되었다는 논리로, 정부주도로 국정교과서로 환원하려는 움직임이 일고 있다.", image: "http://pub.chosun.com/editor/cheditor_new/attach/QAPOYF6PIY67QAKCQCHI_1.jpg")
Point.create(user_id: 1, debate_id: 1, title: "기존의 검정 교과서 체제를 보완하는 것으로는 불가능한 문제인가?")
Reason.create(user_id: 1, point_id: 1, title: "모두가 인정할 수 있는 하나의 교과서로 전 국민이 배워야, 사회적 통합을 이룰 수 있다.", content: "", is_pros: true)
Reason.create(user_id: 1, point_id: 1, title: "검정 교과서의 문제로 꼽혔던 중요 사건, 인물이 누락된 문제는 해당 부분을 검정 기준에 포함하면 해결 될 문제.", content: "", is_pros: false)
Point.create(user_id: 1, debate_id: 1, title: "기존의 검정 교과서가 정치적 균형을 잃었는가?")
Reason.create(user_id: 1, point_id: 2, title: "7개의 역사교과서의 편향성", content: "", is_pros: true)
Reason.create(user_id: 1, point_id: 2, title: "학생들이 한국 역사를 부정적으로 인식함", content: "", is_pros: true)
Reason.create(user_id: 1, point_id: 2, title: "북한에 대해 지나치게 우호적으로 서술함", content: "", is_pros: true)
Reason.create(user_id: 1, point_id: 2, title: "현행 검정교과서는 이명박정부에서 집필기준마련, 박근혜정부에서 검정됨.", content: "", is_pros: false)
Point.create(user_id: 1, debate_id: 1, title: "국정화 교과서는 정치적으로 중립을 유지할 수 있는가?")
Reason.create(user_id: 1, point_id: 3, title: "중립적이고 모두가 인정할 수 있는 교과서로 기술할 것", content: "", is_pros: true)
Reason.create(user_id: 1, point_id: 3, title: "현행 검정 교과서들이 ‘좌편향'되었다고 규정하고 시작한 국정화이니, 자연스레 ‘우편향’ 될 것", content: "", is_pros: false)
Point.create(user_id: 1, debate_id: 1, title: "학계에서 논쟁되는 내용을 하나의 교과서에 통합한다면 그 유익/해악은?")
Reason.create(user_id: 1, point_id: 4, title: "중립적이고 모두가 인정할 수 있는 교과서를 만들 것", content: "", is_pros: true)
Reason.create(user_id: 1, point_id: 4, title: "역사는 다양한 각도에서 접근해 생각하는 힘을 기르는 과목", content: "", is_pros: false)
Reason.create(user_id: 1, point_id: 4, title: "역사해석은 쉽게 논쟁의 여지가 좁혀지지 않으며, 단일화는 결국 한가지 학설만을 가르치겠다는 이야기", content: "", is_pros: false)
Point.create(user_id: 1, debate_id: 1, title: "분단된 국가에서는 국정화 교과서가 필요한가?")
Reason.create(user_id: 1, point_id: 5, title: "남북분단상황에서 국사만큼은 통일된 역사 인식 필요", content: "", is_pros: true)
Reason.create(user_id: 1, point_id: 5, title: "국가 통합 및 국력 강화", content: "", is_pros: true)
Reason.create(user_id: 1, point_id: 5, title: "서독은 통일 이전 검정교과서를 사용", content: "", is_pros: false)
Reason.create(user_id: 1, point_id: 5, title: "우리나라 분단 직후에는 검정교과서 사용", content: "", is_pros: false)
Point.create(user_id: 1, debate_id: 1, title: "이웃 나라와 역사 분쟁에서 자유로운가?")
Reason.create(user_id: 1, point_id: 6, title: "별개의 문제", content: "", is_pros: true)
Reason.create(user_id: 1, point_id: 6, title: "일본의 검정교과서를 비난할 정당성조차 잃게 된다.", content: "", is_pros: false)
Point.create(user_id: 1, debate_id: 1, title: "국정화 교과서가 기존 검정 교과서보다 높은 질로 만들어지는가?")
Reason.create(user_id: 1, point_id: 7, title: "자격있는 집필진을 엄선하여 수준높게 만들 것.", content: "", is_pros: true)
Reason.create(user_id: 1, point_id: 7, title: "시간 부족, 졸속으로 만들어 질 것", content: "", is_pros: false)
Reason.create(user_id: 1, point_id: 7, title: "역사학자 대다수가 반대, 집필진 부족으로 질 보장할 수 없음", content: "", is_pros: false)
Point.create(user_id: 1, debate_id: 1, title: "국정화 시 수정될 것으로 보이는 지점들은?")
Reason.create(user_id: 1, point_id: 8, title: "아직 집필 시작하지 않음. 불확실", content: "", is_pros: true)
Reason.create(user_id: 1, point_id: 8, title: "군사쿠데타 미화", content: "", is_pros: false)
Reason.create(user_id: 1, point_id: 8, title: "이승만을 건국 대통령으로", content: "", is_pros: false)
